Models/Drivers/DriverViewModel.cs
namespace KaldAndCocaine.Models.Drivers
{
    public class DriverViewModel
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public DateTime DateOfBirth { get; set; }
    }
}

Models/ErrorViewModel.cs
namespace KaldAndCocaine.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/DriverController.cs
using KaldAndCocaine.Models.Drivers;
using Microsoft.AspNetCore.Mvc;

namespace KaldAndCocaine.Controllers
{
    public class DriverController : Controller
    {
        public IActionResult Index()
        {
            List<DriverViewModel> drivers = new List<DriverViewModel>();

            DriverViewModel driver = new DriverViewModel();
            driver.Id = 3;
            driver.FirstName = "Khalid";
            driver.LastName = "Kata";
            driver.DateOfBirth = new DateTime(1993, 12, 12);
            drivers.Add(driver);

            DriverViewModel driver2 = new DriverViewModel();
            driver2.Id = 17;
            driver2.FirstName = "Khalid";
            driver2.LastName = "Kata";
            driver2.DateOfBirth = new DateTime(1993, 12, 12);
            drivers.Add(driver2);

            return View(drivers);
        }

        public IActionResult DriverDetails()
        {
            DriverViewModel driver = new DriverViewModel();
            driver.Id = 17;
            driver.FirstName = "Sameer";
            driver.LastName = "Abu Laila";
            
            driver.DateOfBirth = new DateTime(1994, 8, 25);

            return View(driver);
        }
    }
}

Controllers/HomeController.cs
using KaldAndCocaine.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace KaldAndCocaine.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Driver/DriverDetails.cshtml
@using KaldAndCocaine.Models.Drivers
@model DriverViewModel

<h1>Driver Details</h1>
<div class="row">
    <div class="col-md-2">
        Id
    </div>
    <div class="col-md-4">
        @Model.Id
    </div>
</div>

<div class="row mt-2">
    <div class="col-md-2">
        Name
    </div>
    <div class="col-md-4">
        @Model.FirstName @Model.LastName
    </div>
</div>

<div class="row mt-2">
    <div class="col-md-2">
        Date of Birth
    </div>
    <div class="col-md-4">
        @Model.DateOfBirth
    </div>
</div>

Views/Driver/Index.cshtml
@using KaldAndCocaine.Models.Drivers
@model List<DriverViewModel>

<h1>Drivers List</h1>

@foreach (DriverViewModel driver in Model)
{    
    <div class="row">
        <div class="col-md-2">
            Id
        </div>
        <div class="col-md-4">
            @driver.Id
        </div>
    </div>

    <div class="row mt-2">
        <div class="col-md-2">
            Name
        </div>
        <div class="col-md-4">
            @driver.FirstName @driver.LastName
        </div>
    </div>

    <div class="row mt-2">
        <div class="col-md-2">
            Date of Birth
        </div>
        <div class="col-md-4">
            @driver.DateOfBirth
        </div>
    </div>
    
    <hr />
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<img src="~/images/Cyclops_1_Submersible.jpg" alt="" />

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - KaldAndCocaine</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/KaldAndCocaine.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">KaldAndCocaine</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Driver" asp-action="Index">Drivers</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">

            @RenderBody()

        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - KaldAndCocaine - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>